CREATE SCHEMA IF NOT EXISTS WATER_LEVEL_MONITORING_UK;

CREATE TABLE IF NOT EXISTS WATER_LEVEL_MONITORING_UK.STATIONS (
    "ID_KEY" SERIAL PRIMARY KEY,
    "RLOIID" VARCHAR(255),
    "LABEL" VARCHAR(255),
    "MEASURES_ID" VARCHAR(255),
    "NOTATION" VARCHAR(255),
    "RIVERNAME" VARCHAR(255),
    "TYPICALRANGEHIGH" FLOAT,
    "TYPICALRANGELOW" FLOAT,
    "TOWN" VARCHAR(255),
    "LAT" FLOAT,
    "LONG" FLOAT
);

CREATE TABLE IF NOT EXISTS WATER_LEVEL_MONITORING_UK.MEASUREMENTS (
    "ID_KEY" SERIAL PRIMARY KEY,
    "ID" VARCHAR(255),
    "STATIONREFERENCE" VARCHAR(255),
    "DATETIME" TIMESTAMP,
    "VALUE" FLOAT,
    "UNIT" VARCHAR(255)
);