services:
  # airflow
  # cassandra
  json-api:
  kafka:
  kafka-create-topic:
  kafka-ui:
  # postgres:
  # python-producer:
  # spark:
  # streamlit:
  # tensorflow:
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      streaming-pipeline:
        ipv4_address: 172.18.0.1

networks:
  streaming-pipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"