services:
  # airflow
  # cassandra
  json-api:
  
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS = PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS = PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      streaming-pipeline:
        ipv4_address: 172.18.0.2

  kafka-create-topic:
    image: 'bitnami/kafka:latest'
    command: [ "/bin/bash", "-c", "/kafka-setup.sh"]
    environment:
      - TOPIC_NAME=stations
      - BOOTSTRAP_SERVER=kafka:9092
    volumes:
      - type: bind
        source: ./kafka-topic/kafka-topic-setup.sh
        target: /kafka-topic-setup.sh
    depends_on:
      kafka:
        condition: service_started
    networks:
      streaming-pipeline:
        ipv4_address: 172.18.0.4
    
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.6.2
    ports:
      - 8888:8888
    environment:
      KAFKA_CLUSTERS_0_NAME: monitoring-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://:9092,PLAINTEXT://kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
    networks:
      streaming-pipeline:
        ipv4_address: 172.18.0.3

  # postgres:
  # python-producer:
  # spark:
  # streamlit:
  # tensorflow:
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      streaming-pipeline:
        ipv4_address: 172.18.0.1

networks:
  streaming-pipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"