services:
  # airflow
  # cassandra
  json-api:
  kafka:
  kafka-create-topic:
  kafka-ui:
  # postgres:
  # python-producer:
  # spark:
  # streamlit:
  # tensorflow:
  zookeeper:
networks:
  streaming-pipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"